### ISSUE TITLE
Doesn't work with the new metalsmith-layouts (replaces metalsmith-templates)

### ISSUE THREAD

**Issue by jarodtaylor** [pjeby/gulpsmith#14]
Everything in my gulpsmith app was running smoothly until I updated from the now deprecated templating system [metalsmith-templates](https://github.com/segmentio/metalsmith-templates) to [metalsmith-layouts](https://github.com/superwolff/metalsmith-layouts).

When trying to run my build, I get the following error:

```
/Users/A627526/Sites/jarodtaylor_metalsmith/node_modules/gulpsmith/node_modules/vinyl/index.js:110
      throw new Error("File.contents can only be a Buffer, a Stream, or null."
            ^
Error: File.contents can only be a Buffer, a Stream, or null.
    at File.Object.defineProperty.set (/Users/A627526/Sites/jarodtaylor_metalsmith/node_modules/gulpsmith/node_modules/vinyl/index.js:110:13)
    at new File (/Users/A627526/Sites/jarodtaylor_metalsmith/node_modules/gulpsmith/node_modules/vinyl/index.js:25:17)
    at Function.gulpsmith.to_vinyl (/Users/A627526/Sites/jarodtaylor_metalsmith/node_modules/gulpsmith/gulpsmith.js:211:18)
    at /Users/A627526/Sites/jarodtaylor_metalsmith/node_modules/gulpsmith/gulpsmith.js:124:43
    at Metalsmith.<anonymous> (/Users/A627526/Sites/jarodtaylor_metalsmith/node_modules/gulpsmith/gulpsmith.js:127:17)
    at Immediate._onImmediate (/Users/A627526/Sites/jarodtaylor_metalsmith/node_modules/metalsmith/node_modules/unyield/node_modules/co/index.js:52:14)
    at processImmediate [as _immediateCallback] (timers.js:367:17)

```

I looked around and saw that someone reported this on [metalsmith-layout's issue tracker](https://github.com/superwolff/metalsmith-layouts/issues/41), but it wasn't resolved. They forwarded this person back here.

**Comment by pjeby** [comment]
I've confirmed by source review that this is a bug in metalsmith-layout: files without a layout aren't converted back to buffers, they're left as strings.

**Comment by jarodtaylor** [comment]
Thanks for the prompt reply, @pjeby. I'll head back to metalsmith-layout.
