### ISSUE TITLE
gulpsmith with gulp v4

### ISSUE THREAD

**Issue by ThePeach** [pjeby/gulpsmith#17]
As reported in https://github.com/totocaster/metalsmith-tags/issues/53#issuecomment-355553337 with the release of gulp 4 and the new dependency of vinyl-fs v3 some things might have been broken for some plugins.

I've tested the plugins separately from gulp and they don't have any problems per-se, so I'm guessing this is something related to gulpsmith alone.

**Comment by pjeby** [comment]
Per #18, try the `vinyl2` branch and let me know if it works.  I do not use gulp4 myself nor am I currently using gulpsmith, so it's a bit difficult to know if the changes I've made are sufficient.

(The error you're encountering is simply that gulpsmith is using an older vinyl version than gulp 4; changing the dependency breaks gulpsmith's tests, though, because it has more private properties than the older vinyl.  I've updated the property map, but am uncertain whether that's enough to make vinyl2 file objects work correctly.)

So, please give the branch a try and let me know if it works for you.

**Comment by ThePeach** [comment]
hi @pjeby, good to hear!
I've tried installing it via:

    $ npm install --save-dev github:pjeby/gulpsmith#vinyl2

but when running it I get:

```
[18:52:10] Starting 'metalsmith'...
[18:52:10] 'metalsmith' errored after 53 ms
[18:52:10] Error: Cannot find module 'gulpsmith'
    ...
    at metalsmith (/home/peach/public_html/blog.smartart.it-static/gulpfile.js:112:21)
    ...
```

at line 112 I have:

      const gulpsmith = require('gulpsmith');

I've probably forgot something absolutely stupid

**Comment by pjeby** [comment]
The .js version isn't in revision control, so you need to:

```
cd node_modules/gulpsmith
npm install
npm run prepublish
cd -
```

**Comment by ThePeach** [comment]
here's the output:

```
[peach@figtree blog.smartart.it-static]$ cd node_modules/gulpsmith
[peach@figtree gulpsmith]$ npm install
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated coffee-script@1.7.0: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@2.0.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soonas possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soonas possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN prepublish-on-install As of npm@5, `prepublish` scripts are deprecated.
npm WARN prepublish-on-install Use `prepare` for build steps and `prepublishOnly` for upload-only.
npm WARN prepublish-on-install See the deprecation note in `npm help scripts` for more information.

> gulpsmith@0.6.0 prepublish /home/peach/public_html/blog.smartart.it-static/node_modules/gulpsmith
> gulp build

[22:13:31] Working directory changed to ~/public_html/blog.smartart.it-static
[22:13:32] Using gulpfile ~/public_html/blog.smartart.it-static/gulpfile.js
/home/peach/public_html/blog.smartart.it-static/node_modules/gulpsmith/node_modules/gulp/bin/gulp.js:129
    gulpInst.start.apply(gulpInst, toRun);
                   ^

TypeError: Cannot read property 'apply' of undefined
    at /home/peach/public_html/blog.smartart.it-static/node_modules/gulpsmith/node_modules/gulp/bin/gulp.js:129:20
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:678:11)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gulpsmith@0.6.0 prepublish: `gulp build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the gulpsmith@0.6.0 prepublish script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/peach/.npm/_logs/2018-01-05T22_13_32_496Z-debug.log
[peach@figtree gulpsmith]$ npm run prepublish

> gulpsmith@0.6.0 prepublish /home/peach/public_html/blog.smartart.it-static/node_modules/gulpsmith
> gulp build

[22:13:32] Working directory changed to ~/public_html/blog.smartart.it-static
[22:13:33] Using gulpfile ~/public_html/blog.smartart.it-static/gulpfile.js
/home/peach/public_html/blog.smartart.it-static/node_modules/gulpsmith/node_modules/gulp/bin/gulp.js:129
    gulpInst.start.apply(gulpInst, toRun);
                   ^

TypeError: Cannot read property 'apply' of undefined
    at /home/peach/public_html/blog.smartart.it-static/node_modules/gulpsmith/node_modules/gulp/bin/gulp.js:129:20
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:678:11)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gulpsmith@0.6.0 prepublish: `gulp build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the gulpsmith@0.6.0 prepublish script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/peach/.npm/_logs/2018-01-05T22_13_33_875Z-debug.log
```

**Comment by pjeby** [comment]
Looks like you can't do a git checkout with npm if a prepublish script is needed.  So here's a `gulpsmith.js` you can copy to `node_modules/gulpsmith/`, then: https://gist.github.com/pjeby/cffe5e8bc7fa4d6f23e0b8f6aabec49b

**Comment by ThePeach** [comment]
works flawlessly, thanks for this

**Comment by pjeby** [comment]
Ok, it's now up on npm as gulpsmith 0.6.0, so I think we're done here.
