### ISSUE TITLE
Front Matter and File Properties problems

### ISSUE THREAD

**Issue by plankguy** [pjeby/gulpsmith#3]
First off great plugin! I'm following your _Front Matter and File Properties_ instructions but i'm getting a stream error: `gulp-front-matter: Cannot get the front matter in a stream` which is being thrown by `node_modules/gulp-front-matter/node_modules/event-stream/node_modules/map-stream/index.js:103` (i've pasted the entire error at the bottom of this issue).

I was wondering if you might have an idea of what the problem might be.

This is my gulpfile:

```
// Define Gulp dependencies
var gulp        = require('gulp'),
    compass     = require('gulp-sass'),
    watch       = require('gulp-watch'),
    frontMatter = require('gulp-front-matter');
    assign      = require('lodash').assign;

// Define Metalsmith dependencies (migrated from old project, prune as needed)
var Metalsmith  = require('metalsmith'),
    markdown    = require('metalsmith-markdown'),
    templates   = require('metalsmith-templates'),
    watch       = require('metalsmith-watch'),
    gulpsmith   = require('gulpsmith')
    permalinks  = require('metalsmith-permalinks');

// Define paths
var paths = {
    base : './',
    src  : {
        base        : './src',
        static      : './src/static',
        sass        : './src/static/scss',
        css         : './src/static/css',
        images      : './src/static/images',
        content     : './src/content',
        templates   : './src/templates'
    },
    dest : {
        base        : './www',
        static      : './www/static',
        css         : './www/static/css',
        images      : './www/static/images',
        content     : './www/content',
    }
}

gulp.task('metalsmith', function() {

    gulp.src([
        paths.src.css+'/**/*',
        paths.src.content+'/**/*',
        paths.src.images+'/**/*',
    ])
        .pipe( frontMatter() ).on('data', function(file) {
            assign(file, file.frontMatter); 
            delete file.frontMatter;
        })
        .pipe(
            gulpsmith()
            .use( markdown({
                gfm:    true,
                tables: true
            }))
            // Use Swig templates
            .use( templates({
                engine:     'swig',
                directory:  paths.src.templates+'/pages'
            }))
            // Permalinks
            .use( permalinks({
                pattern: ':title' // To do: nest in /blog/
            }))
            // You can initialize the metalsmith instance with metadata
            .metadata( { site_name: 'Metalsmith Gulp' } )
        )
        //.pipe(another_gulp_plugin(more_options))
        .pipe( gulp.dest( paths.dest.base ) );
});
```

Entire error:

```
Error: gulp-front-matter: Cannot get the front matter in a stream
    at /metalsmith-gulp/node_modules/gulp-front-matter/index.js:30:17
    at wrappedMapper (/metalsmith-gulp/node_modules/gulp-front-matter/node_modules/event-stream/node_modules/map-stream/index.js:84:19)
    at Stream.stream.write (/metalsmith-gulp/node_modules/gulp-front-matter/node_modules/event-stream/node_modules/map-stream/index.js:96:21)
    at write (/metalsmith-gulp/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:623:24)
    at flow (/metalsmith-gulp/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:632:7)
    at DestroyableTransform.pipeOnReadable (/metalsmith-gulp/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:664:5)
    at DestroyableTransform.emit (events.js:92:17)
    at emitReadable_ (/metalsmith-gulp/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:448:10)
    at emitReadable (/metalsmith-gulp/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:444:5)
    at readableAddChunk (/metalsmith-gulp/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:187:9)
```

I'm relatively new to both Metalsmith and Gulp, so please be gentle. Any feedback is also appreciated!

**Comment by walkerrandolphsmith** [comment]
Maybe [gulp-filter](https://www.npmjs.com/package/gulp-filter/) makes sense here.
